# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/utils/02_analysis_utils.ipynb.

# %% auto 0
__all__ = ['link_coord2dim']

# %% ../../notebooks/utils/02_analysis_utils.ipynb 2
import polars as pl

# %% ../../notebooks/utils/02_analysis_utils.ipynb 3
def link_coord2dim(df: pl.DataFrame, dim="time", coord: str = "radial_distance"):
    """Link the coord to a dimension across different subgroups

    Note: this idea is borrowed from the `xarray.DataArray.coords`.
    """
    base_df = df.filter(sat="JNO").select(dim, coord).rename({coord: f"ref_{coord}"})
    return df.join(base_df, on=dim, how="left")
