# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/utils/20_pds.ipynb.

# %% auto 0
__all__ = ['pds_download']

# %% ../../notebooks/utils/20_pds.ipynb 1
from .. import PARAMS

import pooch
from pooch import Unzip

# %% ../../notebooks/utils/20_pds.ipynb 4
def pds_download(
    mission,  # planetary missions
    instrument,
    dataset,  # Dataset may correspond to a phase of the mission
    coord,
    datatype,
    path,
    sat = None  # satellite name, for missions with multiple satellites
) -> list[str]:
    "Downloading file from PDS server"
    pds_url = PARAMS["pds-download-url"]
    phase_url = PARAMS[mission][instrument][dataset]["url_format"]
    url = f"{pds_url}/{phase_url}/{coord}/{datatype}"

    files = pooch.retrieve(
        url=url,
        known_hash=None,
        path=path,
        processor=Unzip(
            extract_dir=f"{mission}/{instrument}/{dataset}/{coord}/{datatype}"
        ),
    )

    return files
