# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/missions/juno/state.ipynb.

# %% auto 0
__all__ = ['bcols_hgi', 'bcols_rtn', 'vcols_hgi', 'vcols_rtn', 'load_inputs', 'load_data', 'preprocess_data', 'hgi2rtn',
           'process_data', 'create_pipeline']

# %% ../../../notebooks/missions/juno/state.ipynb 1
from datetime import timedelta
import polars as pl
import pandas

from kedro.pipeline import Pipeline, node
from kedro.pipeline.modular_pipeline import pipeline

# %% ../../../notebooks/missions/juno/state.ipynb 4
def load_data(
    raw_data: pandas.DataFrame,
    start: str,
    end: str,
) -> pl.LazyFrame:
    return pl.from_pandas(raw_data).lazy()

# %% ../../../notebooks/missions/juno/state.ipynb 6
def preprocess_data(
    raw_data: pl.LazyFrame,
) -> pl.DataFrame:
    """
    Preprocess the raw dataset (only minor transformations)

    - Parsing and typing data (like from string to datetime for time columns)
    - Changing storing format (like from `csv` to `parquet`)
    """
    df = (
        raw_data
        .with_columns(
            time=pl.col("Date_Time").str.to_datetime(time_unit="ns"),
        )
        .sort("time")
        .drop(["Date_Time", "hour"])
    ).collect()
    return df

# %% ../../../notebooks/missions/juno/state.ipynb 8
bcols_hgi = ["bx", "by", "bz"]
bcols_rtn = ["b_r", "b_t", "b_n"]
vcols_hgi = ["ux", "uy", "uz"]
vcols_rtn = ["v_r", "v_t", "v_n"]


def hgi2rtn(df: pl.LazyFrame | pl.DataFrame):
    """Transform coordinates from HGI to RTN"""

    phi_rad = pl.col("phi_rad")
    ux = pl.col("ux")
    uy = pl.col("uy")
    uz = pl.col("uz")
    result = (
        df.with_columns(
            phi_rad=pl.col("phi").radians(),
        )
        .with_columns(
            b_r=pl.col("bx") * phi_rad.cos() + pl.col("by") * phi_rad.sin(),
            b_t=-pl.col("bx") * phi_rad.sin() + pl.col("by") * phi_rad.cos(),
            b_n=pl.col("bz"),
            v_r=ux * phi_rad.cos() + uy * phi_rad.sin(),
            v_t=-ux * phi_rad.sin() + uy * phi_rad.cos(),
            v_n=uz,
            plasma_speed=(ux**2 + uy**2 + uz**2).sqrt(),
        )
        .drop(["phi", "phi_rad"] + bcols_hgi + vcols_hgi)
    )
    return result

# %% ../../../notebooks/missions/juno/state.ipynb 9
def process_data(
    raw_data: pl.DataFrame,
    ts = None,  # time resolution
) -> pl.DataFrame:
    """
    Corresponding to primary data layer, where source data models are transformed into domain data models

    - Transforming data to RTN (Radial-Tangential-Normal) coordinate system
    - Applying naming conventions for columns
    """

    columns_name_mapping = {
        "r": "radial_distance",
        "v_r": "v_x",
        "v_t": "v_y",
        "v_n": "v_z",
        "b_r": "model_b_r",
        "b_n": "model_b_n",
        "b_t": "model_b_t",
        "Ti": "plasma_temperature",
        "rho": "plasma_density",
    }

    return raw_data.pipe(hgi2rtn).rename(columns_name_mapping)

# %% ../../../notebooks/missions/juno/state.ipynb 11
from ..default.data import create_pipeline_template

load_inputs = dict(
    raw_data="model_data",
    start="params:start_date",
    end="params:end_date",
)

def create_pipeline(sat_id="JNO", source="STATE"):
    return create_pipeline_template(
        sat_id=sat_id,
        source=source,
        load_data_fn=load_data,
        preprocess_data_fn=preprocess_data,
        process_data_fn=process_data,
        load_inputs=load_inputs,
    )
