name: discontinuitypy
channels:
  - conda-forge
dependencies:
  - pandas
  - polars
  # - modin-ray # not working on Apple Silicon
  - pdpipe

  - xarray
  # For accelerating xarray
  - scipy
  - bottleneck
  - numbagg
  - flox # fast & furious GroupBy reductions for xarray and dask
  
  - astropy
  - plasmapy

  - jupyter
  - fastai::fastcore

  - hvplot

  - loguru
  - tqdm
  - pip
  - pip:
    - pyspedas # needed for plotting (to be removed in the future)
    # - swifter # efficiently applies any function to a pandas dataframe or series in the fastest available manner
    - multipledispatch
    - xarray-einstats
    # - ../space_analysis
    # - . # local package