[tool.kedro]
package_name = "ids_finder"
project_name = "ids_finder"
kedro_init_version = "0.18.13"
source_dir = '.'

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/ids_finder -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
