# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_base.ipynb.

# %% auto 0
__all__ = ['ROOT_DIR', 'PARAMS']

# %% ../notebooks/00_base.ipynb 1
__version__ = "0.0.1"

# %% ../notebooks/00_base.ipynb 2
from pathlib import Path

# %% ../notebooks/00_base.ipynb 3
#| eval: false
ROOT_DIR = Path(__file__).parent.parent

# %% ../notebooks/00_base.ipynb 6
from .utils.basic import load_params
PARAMS = load_params()
