project:
  type: website
  preview: 
    port: 5556

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: "https://github.com/Beforerr/ids_finder"
  sidebar:
    style: floating
    contents:
      - auto: true
      # - auto: "/*.ipynb"
      # - section: Missions
        # contents: missions/*
      # - section: Analysis
        # contents: analysis/*

bibliography: '../../research.bib'

metadata-files: [nbdev.yml]