project:
  type: website
  resources: 
    - "*.html"

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.ipynb
      # - text: "Get Started"
      #   href: getting_started.ipynb
      # - text: "Tutorial"
      #   href: tutorials/tutorial.ipynb
    right:
      - icon: github
        href: "https://github.com/Beforerr/ids_finder"
  sidebar:
    style: floating


metadata-files: [nbdev.yml, sidebar.yml]