project:
  type: website
  resources: 
    - "*.html"

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Results"
        href: analysis/index.qmd
      # - text: "Tutorial"
      #   href: tutorials/tutorial.ipynb
    right:
      - icon: github
        href: "https://github.com/Beforerr/ids_finder"
  sidebar:
    style: floating
    contents:
      - auto: "/*.ipynb"
      - section: Missions
        contents: missions/*
      - section: Analysis
        contents: analysis/*

metadata-files: [nbdev.yml]