project:
  type: website

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: "https://github.com/Beforerr/ids_finder"
  sidebar:
    style: floating
    contents:
      - auto: true
      # - auto: "/*.ipynb"
      # - section: Missions
        # contents: missions/*
      # - section: Analysis
        # contents: analysis/*

metadata-files: [nbdev.yml]