# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/missions/themis.ipynb.

# %% auto 0
__all__ = ['ThemisConfigBase']

# %% ../../notebooks/missions/themis.ipynb 0
from ..datasets import IDsDataset
from space_analysis.meta import MagDataset, PlasmaDataset
from space_analysis.missions.themis import thb_l2_fgm, thb_l2_mom

# %% ../../notebooks/missions/themis.ipynb 1
class ThemisConfigBase(IDsDataset):
    name: str = "THEMIS"
    mag_meta: MagDataset = thb_l2_fgm
    plasma_meta: PlasmaDataset = thb_l2_mom
