# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../../notebooks/99_pipelines.ipynb.

# %% auto 0
__all__ = ['combine_candidates', 'create_pipeline']

# %% ../../../../notebooks/99_pipelines.ipynb 3
def combine_candidates(dict):
    pass

# node_thm_extract_features = node(
#     extract_features,
#     inputs=["primary_thm_rtn_1s", "params:tau", "params:thm_1s_params"],
#     outputs="candidates_thm_rtn_1s",
#     name="extract_ARTEMIS_features",
# )

# node_combine_candidates = node(
#     combine_candidates,
#     inputs=dict(
#         sta_candidates="candidates_sta_rtn_1s",
#         jno_candidates="candidates_jno_ss_se_1s",
#         thm_candidates="candidates_thm_rtn_1s",
#     ),
#     outputs="candidates_all_1s",
#     name="combine_candidates",
# )

# %% ../../../../notebooks/99_pipelines.ipynb 4
from kedro.pipeline import Pipeline, pipeline, node

def create_pipeline(**kwargs) -> Pipeline:
    pass
#     thm_pipeline = pipeline(
#         [
#             node_thm_extract_features,
#         ]
#     )
#     return (
#         + thm_pipeline
#     )
