tau: 60 # unit: seconds
detection:
  index_std_threshold: 2
  index_fluc_threshold: 1
  index_diff_threshold: 0.1
jno_start_date: "2011-08-25"
jno_end_date: "2016-06-30"

mission:
  source:
    time_resolution: 1 # unit: seconds
