tau: 60
jno_start_date: "2011-08-25"
jno_end_date: "2016-06-30"

# To be depreciated
jno_1s_params:
  bcols: ["BX", "BY", "BZ"]
  data_resolution: 1

jno.extract_params:
  bcols: ["BX", "BY", "BZ"]
  data_resolution: 1

sta.extract_params:
  bcols: ["BX", "BY", "BZ"]
  data_resolution: 1


omni_vars:
  "N":
    COLNAME: "sw_density"
    FIELDNAM: "Ion density"
    UNITS: "Per cc"
  "T":
    COLNAME: "sw_temperature"
    FIELDNAM: "Plasma temperature"
    UNITS: "K"
  "V":
    COLNAME: "sw_speed"
    FIELDNAM: "Flow speed"
    UNITS: "km/s"
  "THETA-V":
    COLNAME: "sw_vel_theta"
    FIELDNAM: "Flow latitude"
    UNITS: "Deg"
  "PHI-V":
    COLNAME: "sw_vel_phi"
    FIELDNAM: "Flow longitude"
    UNITS: "Deg"