# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/missions/wind/mag.ipynb.

# %% auto 0
__all__ = ['download_data', 'load_data', 'create_partitions', 'preprocess_data', 'process_data', 'create_pipeline']

# %% ../../../notebooks/missions/wind/mag.ipynb 1
from datetime import timedelta
import polars as pl

from ...utils.basic import cdf2pl, pmap, resample
from ..default.data_mag import create_pipeline_template

from functools import partial

from typing import Dict, Callable

# %% ../../../notebooks/missions/wind/mag.ipynb 4
import pyspedas

def download_data(start: str, end: str, datatype="h4-rtn") -> list[str]:
    trange = [start, end]
    return pyspedas.wind.mfi(trange, datatype=datatype, downloadonly=True)

# %% ../../../notebooks/missions/wind/mag.ipynb 5
def load_data(
    start: str = None,
    end: str = None,
    datatype="h4-rtn",
    var_names="BRTN",
):
    files = download_data(start=start, end=end, datatype=datatype)
    load_func = partial(cdf2pl, var_names=var_names)
    
    return pl.concat(files | pmap(load_func))

# %% ../../../notebooks/missions/wind/mag.ipynb 7
def create_partitions(files, func):
    keys = [file.split("/")[-1] for file in files]
    return {key: partial(func, file) for key, file in zip(keys, files)}

# %% ../../../notebooks/missions/wind/mag.ipynb 8
def preprocess_data(
    raw_data,
    var_names="BRTN",
):
    """
    Preprocess the raw dataset (only minor transformations)
    - Applying naming conventions for columns
    """
    
    load_func = partial(cdf2pl, var_names=var_names)
    return create_partitions(raw_data, load_func)

# %% ../../../notebooks/missions/wind/mag.ipynb 10
def process_data(
    raw_data: Dict[str, Callable[..., pl.LazyFrame]],
    ts,  # time resolution, in seconds
):
    every = timedelta(seconds=ts)
    period = 2 * every

    return {
        key: func().pipe(resample, every=every, period=period)
        for key, func in raw_data.items()
    }

# %% ../../../notebooks/missions/wind/mag.ipynb 12
def create_pipeline(sat_id="Wind", source="MAG"):
    return create_pipeline_template(
        sat_id=sat_id,
        source=source,
        load_data_fn=download_data,
        preprocess_data_fn=preprocess_data,
        process_data_fn=process_data,
    )
