# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/missions/stereo/index.ipynb.

# %% auto 0
__all__ = ['create_pipeline']

# %% ../../../notebooks/missions/stereo/index.ipynb 5
#| code-summary: import all the packages needed for the project
#| output: hide
from fastcore.utils import *
from fastcore.test import *
from ...utils.basic import *
from ...core import *

import polars as pl
import pandas
import numpy as np

from datetime import timedelta
from loguru import logger

from typing import Callable, Dict

# %% ../../../notebooks/missions/stereo/index.ipynb 6
from ...core import extract_features

# %% ../../../notebooks/missions/stereo/index.ipynb 8
from kedro.pipeline import Pipeline, node
from kedro.pipeline.modular_pipeline import pipeline

# %% ../../../notebooks/missions/stereo/index.ipynb 11
from ..stereo.mag import create_pipeline as create_mag_data_pipeline
from ..stereo.state import create_pipeline as create_state_data_pipeline
from ..default.mission import create_combined_data_pipeline

# %% ../../../notebooks/missions/stereo/index.ipynb 12
def create_pipeline(
    sat_id="sta",
    tau="60s",
    ts_mag="1s",  # time resolution of magnetic field data
    ts_state="1h",  # time resolution of state data
) -> Pipeline:
    return (
        create_mag_data_pipeline(sat_id, ts=ts_mag, tau=tau)
        + create_state_data_pipeline(sat_id, ts=ts_state)
        + create_combined_data_pipeline(sat_id, tau=tau, ts_state=ts_state)
    )
