# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/missions/psp/mag.ipynb.

# %% auto 0
__all__ = ['download_data', 'load_data']

# %% ../../../notebooks/missions/psp/mag.ipynb 1
import polars as pl

import pyspedas
from ...utils.cdf import cdf2pl
from ...utils.basic import pmap

from functools import partial

# %% ../../../notebooks/missions/psp/mag.ipynb 3
def download_data(**kwargs):
    return pyspedas.psp.fields(downloadonly=True, **kwargs)

# %% ../../../notebooks/missions/psp/mag.ipynb 4
def load_data(
    var_names="psp_fld_l2_mag_RTN",
    **kwargs
):
    files = download_data(**kwargs)
    load_func = partial(cdf2pl, var_names=var_names)
    
    return pl.concat(files | pmap(load_func))
