name: Publishing (GitHub Pages and PyPI)

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    uses: Beforerr/workflows/.github/workflows/pixi_nbdev.yml@main
    secrets: inherit
    permissions: { contents: write }
  pypi-publish:
    uses: Beforerr/workflows/.github/workflows/pypi_publish.yml@main
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      contents: write
